### PR TITLE
Test

### PR DESCRIPTION
**Pull request by sudhay23**

### CODE REVIEW

**Comment by san-coding** [comment]
@sudhay23 will the website be deployed when the the checks pass, or only after PR gets merged or approved

**Comment by sudhay23** [comment]
One min @san-coding

**Comment by san-coding** [comment]
Make @sridhar-5 a maintained / contributor

**Comment by san-coding** [comment]
Changes might reflect in the next PR , once this PR is merged

**Comment by sudhay23** [comment]
Yayyyy

**Pull request closed without merging**
