### PR TITLE
Added animation on landing page

### LINKED ISSUE #51: Animate Landing Page

### PR DESCRIPTION
**Pull request by AwsmNinad25**
**Description**

This PR fixes #51 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by san-coding** [comment]
Please share a screenshot of how the page looks after your changes

**Comment by san-coding** [comment]
I am handling some merge conflicts now, I will merge yours once those are resolved, do share a small video/screenshot

**Comment by AwsmNinad25** [comment]
Ok

**Comment by AwsmNinad25** [comment]
animate
@san-coding Have a look at this.

**Comment by san-coding** [comment]
Thanks @AwsmNinad25 , I will soon merge it

**Comment by san-coding** [comment]
Is it responsive ?

**Comment by san-coding** [comment]
@AwsmNinad25 there was a sticky modal button on the top right corner, I am unable to see that in your video

**Comment by san-coding** [comment]
@AwsmNinad25 I think you might have to wait and make some changes , because @SayantaniDeb is working on the making the nav bar sticky and moving the sticky button to the nav bar or to the bottom right corner, once she completes these two tasks, you can fetch and make your changes, sorry for the inconvenience caused, multiple people working on the landing page is causing merge conflicts, lets wait for @SayantaniDeb to finish, looking forward to merging your PR, the animations look beautiful🎉

**Comment by AwsmNinad25** [comment]
@san-coding 

> Is it responsive ? and is it possible to add the same animations to the customer registration, browse products, and the footer ?

Yup this is responsive and yes it is possible to add animation to customer registration, browse products, and the footer.

**Comment by san-coding** [comment]
> @san-coding
> 
> > Is it responsive ? and is it possible to add the same animations to the customer registration, browse products, and the footer ?
> 
> Yup this is responsive and yes it is possible to add animation to customer registration, browse products, and the footer.

is that button on the top right corner present ?

**Comment by AwsmNinad25** [comment]
> @AwsmNinad25 I think you might have to wait and make some changes , because @SayantaniDeb is working on making the nav bar sticky and moving the sticky button to the nav bar or to the bottom left corner, once she completes these two tasks, you can fetch and make your changes, sorry for the inconvenience caused, multiple people working on the landing page is causing merge conflicts, so don't push anymore commits to this PR, lets wait for @SayantaniDeb to finish, then you can merge those changes and commit your changes to it, looking forward to merging your PR, the animations look beautifultada

Yes, sure I'll wait no problem

**Comment by AwsmNinad25** [comment]
> > @san-coding
> > > Is it responsive ? and is it possible to add the same animations to the customer registration, browse products, and the footer ?
> > 
> > 
> > Yup this is responsive and yes it is possible to add animation to customer registration, browse products, and the footer.
> 
> is that button on the top right corner present ?

no. it isn't

**Comment by AwsmNinad25** [comment]
The nav bar was sticky but no sign of that corner button.

**Comment by san-coding** [comment]
Yeah please wait for a while, It was a mistake on my part , I merged a PR which undid those changes, that's why it doesn't show up, @SayantaniDeb will soon open her PR, I will merge that and then we can work on this, thank you for your patience

**Comment by san-coding** [comment]
I will merge this now and check if everything works , will revert if there is an issue

**Review by san-coding — APPROVED** [review]
Approving it now, will test if this works and get back to you, thanks

**Comment by san-coding** [comment]
Thank you for your time and effort, everything works fine and the animations look amazing 🎉, I request you to open pull request to add animations for forms , browse products and the footer (try to bring out the animations when we scroll down , if possible)

**Pull request merged**
