### PR TITLE
Stickynav scrollbar

### PR DESCRIPTION
**Pull request by SayantaniDeb**
**Description**

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

https://user-images.githubusercontent.com/74983536/135768382-4a277b6d-9c9d-4f8d-8667-0fae7cd52731.mp4

### CODE REVIEW

**Comment by san-coding** [comment]
Thanks , delete line 73, 79, and 81 to solve merge conflict

**Comment by SayantaniDeb** [comment]
If i delete those code then the navbar sticky feature will be removed. So i cant.

**Comment by SayantaniDeb** [comment]
I dont know why its conficting

**Comment by san-coding** [comment]
> If i delete those code then the navbar sticky feature will be removed. So i cant.

I am not telling you to remove everything , remove line 73` <<<<<<<< sticky-nav scrollbar`, similarly 79 and 81

**Comment by san-coding** [comment]
image
Keep any one of them, not both, the commit you just pushed , does that affect the button or nav bar ?

**Comment by SayantaniDeb** [comment]
i need help, i am not able to resolve the conflict even after removing those lines :(

**Comment by san-coding** [comment]
I think you have resolved it now, can you confirm if everything works fine now, I will go ahead and merge

**Comment by SayantaniDeb** [comment]
The code i just deleted is a major code deciding some apt changes, so dont merge it to main

**Comment by san-coding** [comment]
what is the update now?

**Comment by SayantaniDeb** [comment]
yes, now you are good to go

**Comment by san-coding** [comment]
Everything works fine ?

**Comment by SayantaniDeb** [comment]
yes perfect. just like the below video

> **Description**
> 
> **Notes for Reviewers**
> 
> **[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> 
> * [ ]  Yes, I signed my commits.
> 
>  ShopOnline.-.Google.Chrome.2021-10-04.00-42-34.mp4

**Review by san-coding — APPROVED** [review]
Thanks @SayantaniDeb , you have put in a lot of efforts to solve this issue and we are grateful, keep contributing 🎉

**Comment by san-coding** [comment]
Just confirm if this PR is appearing on your hacktoberfest dashboard

**Pull request merged**
