### PR TITLE
add favicon

### LINKED ISSUE #32: Favicon for our website
image
Favicon is the logo that you see on the tab

### PR DESCRIPTION
**Pull request by shreyaansjain06**
**Description**

This PR fixes #32 

**Notes for Reviewers**
Now favicon added

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by ankityadavhere — CHANGES_REQUESTED** [review]
dont put github user uploaded content

**Comment by shreyaansjain06** [comment]
Should i make a img folder and add the favicon image in it

**Comment by ankityadavhere** [comment]
> Should i make a img folder and add the favicon image in it or some other way please tell

first one is correct, but wait till my pr gets merged or we'll have a merge conflict lol as I've already created a `images` folder in `/public`

**Comment by shreyaansjain06** [comment]
ok

**Comment by san-coding** [comment]
Will soon look into this and merge the PRs , thank you for your patience and interest in shoponline👍

**Comment by ankityadavhere** [comment]
> Will soon look into this and merge the PRs , thank you for your patience and interest in shoponline👍

oops, we got merge conflict 😆

**Comment by san-coding** [comment]
@shreyaansjain06 , can you send a screenshot of the changes ? looking forward to merging your PR 🎉

**Comment by ankityadavhere** [comment]
It was just the index.html file that's causing a conflict, as Im done for today 😅, will do the rest tomorrow ✊ @san-coding you can click on merger conflict and see the changes

**Comment by san-coding** [comment]
@shreyaansjain06 I am unable to see any merge conflicts

**Comment by ankityadavhere** [comment]
Oh i think it's wrong issue 😅 my bad, here's the pr #33

**Comment by san-coding** [comment]
Please solve the the merge conflict , if I solve then it won't be counted towards your hacktoberfest PR

**Comment by shreyaansjain06** [comment]
@san-coding  you ask for screenshot here it is
Screenshot 2021-10-02 at 4 29 02 PM

**Comment by san-coding** [comment]
> @san-coding you ask for screenshot here it is Screenshot 2021-10-02 at 4 29 02 PM

I was asking for the screenshot of the changes reflecting in UI

**Comment by san-coding** [comment]
> > @san-coding you ask for screenshot here it is Screenshot 2021-10-02 at 4 29 02 PM
> 
> I was asking for the screenshot of the changes reflecting in UI

I aj asking for screenshot changes reflected in UI

**Comment by san-coding** [comment]
@shreyaansjain06 are you still working on this ? or shall I resolve it and merge

**Comment by shreyaansjain06** [comment]
yes i am working on it
which ui changes you are asking

**Comment by san-coding** [comment]
You have added the favicon to index.html , shot the screenshot of it in the UI , I want to see how the favicon looks  when you open the webpage , add a screenshot of the tab like this

**Comment by san-coding** [comment]
> Resolve merge conflicts by removing line 5, 9 and 56
> image
> send a screenshot of the entire page once everything is resolved

you can resolve the merge conflicts by following this step, thank you

**Comment by san-coding** [comment]
@shreyaansjain06 , no need to add screenshots, I have verified it, looks like the page will load completely only if your branch is up to date with the main because some of the images aren't loading which were added and merged in a separate PR

**Comment by san-coding** [comment]
so you just have to resolve the merge conflicts, looking forward to merge your pull requests🎉

**Comment by shreyaansjain06** [comment]
ok

**Review by san-coding — APPROVED** [review]
Thank you @shreyaansjain06 , we appreciate your efforts and contributions 🎉

**Comment by san-coding** [comment]
Your changes are reflecting and everything works fine, this is the screenshot I was expecting  
image
Thanks 👍🏻

**Pull request merged**
