### PR TITLE
Updated Register and Login Pages

### PR DESCRIPTION
**Pull request by malhaar2002**
image

image

### CODE REVIEW

**Comment by malhaar2002** [comment]
Please approve for Hacktoberfest if you like it

**Comment by san-coding** [comment]
I will look into why the checks are failing and get back to this PR, the UI looks amazing, thank you for your contribution,  will merge this soon

**Comment by san-coding** [comment]
@sudhay23 @sridhar-5

**Comment by sudhay23** [comment]
@san-coding This is strange!!. I don't see a reason for it to fail!?

**Comment by sridhar-5** [comment]
I'll look into it in some time. Currently having breakfast..lol

**Comment by sudhay23** [comment]
@malhaar2002 Can you try opening a new temporary PR with a minute change in the home page trying the checks?

**Comment by sudhay23** [comment]
You may do so from a new branch that you can make

**Comment by san-coding** [comment]
@sudhay23 no need to make test PR, you can always re-run jobs

**Comment by san-coding** [comment]
@malhaar2002 we will fix this soon and merge this PR

**Review by san-coding — APPROVED** [review]
Thank you for your contributions, we appreciate your time and efforts 🎉

**Comment by san-coding** [comment]
@sridhar-5 this bot works fine

**Comment by malhaar2002** [comment]
Thank you :)

**Pull request merged**
