### PR TITLE
Update login.html

### LINKED ISSUE #127: Add GitHub social login button
Reason: 
1) There is a typo in the copyright section on the login page
2) Add Login with the Instagram button on the the page

Screenshot : 
image

### PR DESCRIPTION
**Pull request by mayankgoyal-13**
This PR fixes #127 

## Description
1) Fixed the typo in the copyright section on Login Page
2) Added a "Login with Github" button

## Screenshot
image

## Checks
- [x]  I ensured that my changes are working fine locally
- [ ] I signed my commits (Optional) (Read about [Signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits))

### CODE REVIEW

**Comment by mayankgoyal-13** [comment]
@sudhay23 pls review my pull request and merge it

**Comment by san-coding** [comment]
Please attach a screenshot of your changes, the live preview is not working currently

**Comment by sudhay23** [comment]
@mayankgoyal-13 Can you fetch our branch once for latest updates and push it so this PR gets updated with changes we made

**Comment by mayankgoyal-13** [comment]
> @mayankgoyal-13 Can you fetch our branch once for latest updates and push it so this PR gets updated with changes we made

Done it

**Comment by mayankgoyal-13** [comment]
> Please attach a screenshot of your changes, the live preview is not working currently

Screenshot has been added

**Comment by mayankgoyal-13** [comment]
> > Hooray rockettada The preview version can now be seen on https://shoponline-web.000webhostapp.com/pull_request/
> 
> This one?? @mayankgoyal-13

Yes, I am able to see my changes

**Comment by sudhay23** [comment]
Excellent work... @san-coding can do a final review

**Comment by san-coding** [comment]
@mayankgoyal-13 we can go ahead and merge this as soon as you implement the requested changes

**Comment by mayankgoyal-13** [comment]
> @mayankgoyal-13 we can go ahead and merge this as soon as you implement the requested changes

I have made the changes, please review it

**Pull request closed without merging**
