### PR TITLE
used env variables to load db credentials at runtime using composer library.

### LINKED ISSUE #6: Create .env file and add database credentials to the .env file
#### Description
Import credentials from .env files inside all the relevant PHP files
(credentials are dbname,username,password,etc)

### PR DESCRIPTION
**Pull request by sridhar-5**
**Description**
used vlucas/phpdotenv library to load the database credentials and other credentials at run time.

This PR fixes #6 

**Notes for Reviewers**
Tested the successful working of the environment variables manually using print statements. Attaching the screenshots below. please do check them.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

### This screenshot shows the successful loading of the env variables.

Screenshot 2021-10-04 at 11 18 37 AM

### This screenshot shows the environment variable created locally

Screenshot 2021-10-04 at 11 19 58 AM

### This screenshot shoes the testing method. used 4 echo statements to verify if the env variables are being loaded.
Screenshot 2021-10-04 at 11 20 38 AM

### CODE REVIEW

**Comment by sridhar-5** [comment]
@san-coding can you review this please?

**Review by san-coding — APPROVED** [review]
Thanks @sridhar-5 , we appreciate your efforts and contributions 🎉

**Comment by san-coding** [comment]
This was one of the most valuable contributions, looking forward to more such contributions 🎉

**Comment by sridhar-5** [comment]
Thanks man. Had good time working on this issue. Looking forward...😁😁

**Comment by sudhay23** [comment]
@san-coding Great job :)

**Comment by sridhar-5** [comment]
Thanks @sudhay23

**Comment by sudhay23** [comment]
image

@sridhar-5 This is what I got trying to have it running

**Comment by sridhar-5** [comment]
oh okay I forgot to push the vendor folder man sorry will open a new pull request.

**Comment by sudhay23** [comment]
Lol okkay

**Pull request merged**
