### PR TITLE
Fixed the center issue in the index.html the home page of the app.

### LINKED ISSUE #67: center the get started button
## Get started button is not centered (Make sure the website remains responsive after the change)
image

#### Desired Behavior
Center the button and add the discord link

### PR DESCRIPTION
**Pull request by sridhar-5**
**Description**

This PR fixes #67

**Notes for Reviewers**
The display attribute of the button is set to inline flex which is actually causing this issue of pushing the button to the left end since it's parent is flex and no other elements in the column flex are flex. I over-wrote the display with inline styling, changed the display to 'block' and adding an attribute 'margin' with 0 top and auto on other sides solved the issue.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

### The screenshot of the Homepage after solving the issue..Looks Beautiful...😁

Screenshot 2021-10-04 at 1 12 27 PM

### CODE REVIEW

**Comment by sridhar-5** [comment]
can you please review this @san-coding , @sudhay23 ?

The animations look Very Nice Guys. Really Appreciate it.

**Comment by san-coding** [comment]
Will review post lunch

**Comment by sudhay23** [comment]
@sridhar-5 This looks good. Have you ensured responsiveness too? Does it look decent everywhere?

**Comment by sudhay23** [comment]
Cool then. :)

**Comment by san-coding** [comment]
@sridhar-5 , thank you for your contributions, are you using M1 ?

**Comment by sridhar-5** [comment]
> @sridhar-5 , thank you for your contributions, are you using M1 ?
> 
> 
> 
> 

No man, it's intel i9 one with 8 cores. M1 is still not ready for developers I believe that why I didn't get that..lol

**Comment by san-coding** [comment]
You are from Cbe campus ? which section ?

**Comment by sridhar-5** [comment]
@san-coding Yes, I'm from the Coimbatore campus. 3rd year, CSE-A

**Pull request merged**
