### PR TITLE
Stickynav-scrollbar changes

### LINKED ISSUE #38: Sticky Navbar feature request
#### Current Behavior
The navbar isnt sticky

#### Desired Behavior
The navbar will be made sticky

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by SayantaniDeb**
**Description**

This PR fixes #38 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
what does signing my commits mean? @san-coding

### CODE REVIEW

**Comment by san-coding** [comment]
@SayantaniDeb , there is some issue with the GitHub actions, I am working on it, don't worry about the checks failing

**Review by san-coding — APPROVED** [review]
Thank you  @SayantaniDeb , we appreciate your efforts and contributions, looking forward to more such valuable contributions 🎉

**Comment by SayantaniDeb** [comment]
Thank you. It was great contributing! 👍

**Comment by san-coding** [comment]
@SayantaniDeb signing commits is not mandatory for this repository, but is a good practice to always sign your commits , you can read about [signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by san-coding** [comment]
@SayantaniDeb this has actually undone a PR I had merged before this

**Comment by SayantaniDeb** [comment]
Oh okay, maybe i forgot to fetch

**Comment by SayantaniDeb** [comment]
Can you specify the commit?

**Comment by san-coding** [comment]
Hey @SayantaniDeb , unfortunately , this PR has reverted the changes made by @sudhay23 in PR #52 and #56, @sudhay23 can you please compare your and her changes to figure out we can make both work

**Comment by san-coding** [comment]
it has reverted #56

**Comment by san-coding** [comment]
image
Do you see the floating action button on the top right corner, it is a sticky action button and your changes have undone them

**Comment by SayantaniDeb** [comment]
Okay, I am reverting back the changes and doing it again

**Comment by san-coding** [comment]
Yes thanks, you can first fetch and merge, make sure that sticky button on top right corner is present on the ui before you start making your changes

**Comment by san-coding** [comment]
I will revert this now, thank you for your patience

**Comment by san-coding** [comment]
I suggest you include that sticky button inside the sticky nav if possible , create a new PR, looking forward to merging it 🎉

**Comment by san-coding** [comment]
or feel free to put that sticky button in a appropriate place wherever it looks good, maybe left bottom corner

**Comment by SayantaniDeb** [comment]
https://user-images.githubusercontent.com/74983536/135765456-a70e1123-9189-4dad-a2ac-666e8ea53478.mp4

please review if these changes are the one you wanted

**Comment by SayantaniDeb** [comment]
can you please confirm these changes @san-coding

**Comment by san-coding** [comment]
Yeah thanks , it looks good now

**Comment by san-coding** [comment]
is it possible bring that sticky modal button to bottom left corner ?

**Comment by san-coding** [comment]
Or you can go ahead and create the PR, you have been working on it for a long time, I will take care of shifting that button to the bottom left corner, please go ahead and create the PR

**Comment by SayantaniDeb** [comment]
since this PR is closed i have to create another PR and go forward

**Pull request merged**
