### PR TITLE
To deploy updates to website

### PR DESCRIPTION
**Pull request by sudhay23**
This addresses issue #96

### CODE REVIEW

**Comment by sudhay23** [comment]
@san-coding Can you have a look? Hope it works 😋

**Comment by san-coding** [comment]
@sudhay23 , I guess we will know only once we merge it

**Comment by sudhay23** [comment]
Guess so yeah

**Review by san-coding — APPROVED** [review]
Good job

**Comment by san-coding** [comment]
Is that a workflow that you have added

**Comment by sudhay23** [comment]
Yeah. Upon references

**Pull request merged**
