### PR TITLE
Deploy on PR action

### PR DESCRIPTION
**Pull request by sudhay23**
Deploy on PR action
Addresses #96

### CODE REVIEW

**Comment by sudhay23** [comment]
@san-coding  @sridhar-5  Hope it works now 🤞

**Comment by san-coding** [comment]
WhatsApp down @sridhar-5 @sudhay23 ?

**Comment by sudhay23** [comment]
Oh really... Omg now I know my messages aren't being delivered

**Comment by san-coding** [comment]
Wow it works 🎉

**Comment by sudhay23** [comment]
@san-coding Yayyyyy!!!! We now have it Sandeep

**Comment by sudhay23** [comment]
@san-coding Can you help by doing the honors 😅

**Review by san-coding — APPROVED** [review]
Amazing 🎉, finally we have this setup

**Comment by san-coding** [comment]
Done 🎉

**Pull request merged**
