### PR TITLE
Add animations to buttons

### PR DESCRIPTION
**Pull request by Hrishabh5**
I have added animations to all the buttons which is making them more attractive.

https://user-images.githubusercontent.com/71200145/136157309-452ba8e3-2d65-4694-9401-ab8ac4047ff7.mov

I have applied these animations on other pages as well.

### CODE REVIEW

**Comment by Hrishabh5** [comment]
> Thanks, will merge it soon

Thank you 😊

**Comment by sudhay23** [comment]
@Hrishabh5 Can you do the fetch from our repo again and merge with your branch??

**Comment by Hrishabh5** [comment]
> @Hrishabh5 Can you do the fetch from our repo again and merge with your branch??

Actually, I've just started contributing. So, I don't know how can I do that. Can you please help me?

**Comment by san-coding** [comment]
> > @Hrishabh5 Can you do the fetch from our repo again and merge with your branch??
> 
> Actually, I've just started contributing. So, I don't know how can I do that. Can you please help me?

I you go to your fork, there will be an option to fetch and merge

**Comment by san-coding** [comment]
@sudhay23 why is checkout code failing ?

**Comment by san-coding** [comment]
> > > > @Hrishabh5 Can you do the fetch from our repo again and merge with your branch??
> > > 
> > > 
> > > Actually, I've just started contributing. So, I don't know how can I do that. Can you please help me?
> > 
> > 
> > I you go to your fork, there will be an option to fetch and merge
> 
> Done👍🏻

Join our discord , link in readme, we will assist you with this PR, CI checks are failing for this PR

**Pull request closed without merging**
