### PR TITLE
Added vendor folder to close the issue occurred due to my previous pull request.

### PR DESCRIPTION
**Pull request by sridhar-5**
**Description**

This PR fixes #

**Notes for Reviewers**
Added vendor folder to close the issue occurred due to my previous pull request.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sridhar-5** [comment]
@sudhay23 Merge this it will work.

**Comment by sudhay23** [comment]
@sridhar-5 Cool 🎉 
Are you sure the 'slash' conventions don't matter across Mac and Windows?

**Comment by sridhar-5** [comment]
It's a web app right. for this application it remains the same

**Comment by sridhar-5** [comment]
yeah slash convention are opposite exactly but since this is a web app doesn't matter.

**Comment by san-coding** [comment]
image

**Comment by sudhay23** [comment]
It works 🎉

**Comment by sridhar-5** [comment]
I think this is a project setting up problem. so to be able to use environment variables you need this phpdotenv package. which can be installed using composer.

install composer from here.
https://getcomposer.org/download/

and then 
`composer require --dev vlucas/phpdotenv` execute this after installing composer.

**Comment by sudhay23** [comment]
@sridhar-5 But now since you gave the `/vendor` folder ig it doesn't matter now!?

**Comment by sridhar-5** [comment]
The thing is if you are going ahead and deploying the application then you have to explicitly set the environment variables in what every platforms you are hosting this on.

**Comment by sridhar-5** [comment]
> @sridhar-5 But now since you gave the `/vendor` folder ig it doesn't matter now!?

This is a valid point too. can we have a session sometime and sort this out?

**Comment by sudhay23** [comment]
@sridhar-5 Hop into our discord server 😋 .

**Comment by sridhar-5** [comment]
can you send me an invite?

**Comment by sudhay23** [comment]
https://discord.gg/yhtkaawfNq

**Comment by san-coding** [comment]
@sridhar-5 do you know how to setup live website preview after each commit

**Pull request merged**
