### PR TITLE
Added CONTRIBUTION.md files

### LINKED ISSUE #8: [Docs] Add contribution guidelines for this awesome repository
**Current State:**
There is no contribution.md file
**Desired State:**
Have a contribution.md file with guidelines for contributing to the project

### PR DESCRIPTION
**Pull request by sudhay23**
This PR fixes #8 

**Description**
This repo now has a CONTRIBUTION.md file that helps new contributors get started

### CODE REVIEW

**Comment by sudhay23** [comment]
@san-coding Please verify my updates. Thanks :)

**Review by san-coding — CHANGES_REQUESTED** [review]
Add rules to be followed , add reach out to us message (Our GitHub),

**Comment by sudhay23** [comment]
@san-coding I hope the changes are relevant

**Review by san-coding — APPROVED** [review]
Good job, keep contributing

**Pull request merged**
