### PR TITLE
added a GitHub workflow to greet the first time contributors on this repository.

### LINKED ISSUE #92: Setup GitHub Actions to greet New Contributors
Setup GitHub Actions to greet New Contributors with an image and a welcome message

### PR DESCRIPTION
**Pull request by sridhar-5**
closes #92

### CODE REVIEW

**Comment by sridhar-5** [comment]
@san-coding , @sudhay23 here is it. finally

**Comment by san-coding** [comment]
@sridhar-5 can you help figure out why the build checks are failing

**Review by san-coding — APPROVED** [review]
Thank you @sridhar-5 , had a really productive discussion with you

**Comment by sridhar-5** [comment]
Php composer might fail because there is no php script here and pr greeter fails because I'm not the first time contributor may be. Not sure though lol

**Comment by san-coding** [comment]
@sridhar-5 PR greeter check will pass only after we merge this right ?

**Comment by sridhar-5** [comment]
Also I'm opening an other normal pull request that greets all the users when they open a pull request.

**Comment by sridhar-5** [comment]
> @sridhar-5 PR greeter check will pass only after we merge this right ?

Probably..Not sure..Haven't worked with GitHub actions before...lol

**Pull request merged**
