### PR TITLE
fix: made navbar smaller (#90)

### PR DESCRIPTION
**Pull request by SushantPatial**
Resolves: #90

Please let me know if it needs changes @san-coding

### CODE REVIEW

**Comment by san-coding** [comment]
Will review soon

**Comment by SushantPatial** [comment]
> @SushantPatial Can you fetch the changes from our repository and merge it to your fork one time?

Done that

**Comment by san-coding** [comment]
@SushantPatial do you see your changes reflected in the preview ?

**Comment by san-coding** [comment]
@sudhay23

**Comment by san-coding** [comment]
@SushantPatial share a screenshot

**Comment by san-coding** [comment]
We will merge this in 20 minutes , @SushantPatial thank your for your patience

**Comment by SushantPatial** [comment]
image

Expected: 
image

**Comment by san-coding** [comment]
Thank you

**Review by san-coding — APPROVED** [review]
Thanks @SushantPatial , we appreciate your efforts and contributions , the UI looks good after your changes, keep contributing 🎉

**Comment by SushantPatial** [comment]
I'll make a new issue regarding the hover buttons

**Comment by san-coding** [comment]
Sure go ahead

**Pull request merged**
