### PR TITLE
Added Discord Links to the files

### LINKED ISSUE #45: add discord server invite link to footer in landing page , readme.md and contributions.md
#### Current Behavior
We have a discord server but it is not added to any file
#### Desired Behavior
add discord server invite link to footer in landing page , readme.md and contributions.md

Discord invite link - https://discord.gg/yhtkaawfNq

### PR DESCRIPTION
**Pull request by shashank1503-cipher**
**Description**

This PR fixes #45 

**Notes for Reviewers**
Added Discord link with font-awesome icon in footer beneath social media icon. Added discord link in the Contact Us Section and Created a new Section of Contact us in Readme file for discord link.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by san-coding** [comment]
Thanks, can you add a screenshot of the changes

**Comment by san-coding** [comment]
Please resolve the merge conflict , if I resolve then this won't count towards your hacktoberfest pull request because PRs. should have only your commits

Delete line number 61, 65 and 71 to resolve the merge conflict
image

**Comment by shashank1503-cipher** [comment]
Done.

**Review by san-coding — APPROVED** [review]
Great job, we appreciate your efforts and looking forward to more such contributions 🎉

**Comment by san-coding** [comment]
@shashank1503-cipher I just noticed that you didn't add the discord link to `index.html`, instead you added just added two spaces , since I had to deal with a lot of pull requests that day, I merged it by mistake thinking that you have made the required changes , please explain yourself before your pull request matures in hacktoberfest

**Comment by shashank1503-cipher** [comment]
Hey, Sorry for that
I think i must have switched between main branch and development branch and made a PR without seeing that it has been added or not.......I'll just add it right away.

**Comment by shashank1503-cipher** [comment]
Hey I added a PR for it, kindly review it.
Sorry for previous mistake

**Comment by san-coding** [comment]
Its okay @shashank1503-cipher , mistakes happen to everyone, just make sure you have changed the required files before submitting for review, we value you time and efforts 🎉

**Comment by shashank1503-cipher** [comment]
Thank you!
Happy to Contribute!!!

**Comment by san-coding** [comment]
> Its okay @shashank1503-cipher , mistakes happen to everyone, just make sure you have changed the required files before submitting for review, we value you time and efforts 🎉

Be careful while contributing to other repositories, some maintainers won't give any warning/notification and mark it as spam / invalid, if you're marked spam/invalid twice, you will be disqualified from hacktoberfest

**Pull request merged**
