### PR TITLE
This GitHub Action greets every user who opens a pull request or an issue if the body of the comment is not empty.

### PR DESCRIPTION
**Pull request by sridhar-5**
@san-coding something for you.

### CODE REVIEW

**Comment by sridhar-5** [comment]
currently fails because I still don't have write access to this repository will work just after merging this I guess if it doesn't I'll check and update with new commits.

**Comment by san-coding** [comment]
wait, @sudhay23 make @sridhar-5 a collaborator/maintainer

**Comment by sridhar-5** [comment]
yeah I was about to ask for the same thing. I was waiting to install a GitHub application onto this repository.

**Comment by san-coding** [comment]
@sudhay23 

> wait, @sudhay23 make @sridhar-5 a collaborator/maintainer

**Comment by san-coding** [comment]
come to discord guys, WhatsApp is down

**Pull request merged**
