### PR TITLE
Added social login button on login page

### PR DESCRIPTION
**Pull request by LunlunChin**
Capture

### CODE REVIEW

**Comment by san-coding** [comment]
Does it authenticate you with social login buttons when clicked ?

**Comment by LunlunChin** [comment]
no its just the ui, not sure how to add authentication 😬

**Comment by san-coding** [comment]
> no its just the ui, not sure how to add authentication 😬

That's alright , this is something i was going to implement, now we just need to implement the backend, so i will go ahead and merge this

**Review by san-coding — APPROVED** [review]
Thank you @LunlunChin , we appreciate your efforts and contributions 🎉, keep contributing , star us ⭐️ and help build the community

**Pull request merged**
