### PR TITLE
feat: add meta tags

### LINKED ISSUE #26: [SEO] - Perform fixes to <head> to make the website SEO friendly
- [ ] All necessary Meta tags
- [ ] Twitter meta
- [ ] OpenGraph tags

### PR DESCRIPTION
**Pull request by ankityadavhere**
**Description**
- added all the necessary meta tags to make SEO and search engine friendly 🚀 
This PR fixes #26 

**Notes for Reviewers**
- add images where there is a `<!-- replace with image -->` comment, as I didn't had the images

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ankityadavhere** [comment]
wrong pr, my bad

**Comment by sudhay23** [comment]
@ankityadavhere Great job. As for the images you want, you may use the "cart" logo from our existing hosting link

**Comment by ankityadavhere** [comment]
okay, making changes @sudhay23 👍

**Comment by ankityadavhere** [comment]
hey @sudhay23 , you should merge the folder structure pr cuz if I'll place an image in public folder, this index.html can't get the image until the folder is present, as the folder pr is not merged yet

**Review by sudhay23 — CHANGES_REQUESTED** [review]
Picture is the logo used in header of current hosting

**Comment by ankityadavhere** [comment]
okay ill add the cdn link, but it wont look good as it has a transparent bg 🤔

**Comment by sudhay23** [comment]
> hey @sudhay23 , you should merge the folder structure pr cuz if I'll place an image in public folder, this index.html can't get the image until the folder is present, as the folder pr is not merged yet

That's fine I believe. Bring it to a working state on your machine after whwich all your commits can be merged

**Comment by ankityadavhere** [comment]
> > hey @sudhay23 , you should merge the folder structure pr cuz if I'll place an image in public folder, this index.html can't get the image until the folder is present, as the folder pr is not merged yet
> 
> That's fine I believe. Bring it to a working state on your machine after which all your commits can be merged

done changes!

**Comment by sudhay23** [comment]
Great then :)

**Pull request merged**
