### PR TITLE
create installation_guidelines.md : Add installations steps

### PR DESCRIPTION
**Pull request by Wolfy7**
**Description**

This PR fixes #https://github.com/sudhay23/ShopOnline-Web-App/issues/7

**Notes for Reviewers**

### CODE REVIEW

**Comment by san-coding** [comment]
> **Description**
> 
> This PR fixes ##7
> 
> **Notes for Reviewers**

Thank you for opening the pr and showing interest in shoponline, we are looking for a more detailed installation guidelines file with appropriate screenshots

**Comment by Wolfy7** [comment]
@san-coding  thanks for the feedback.

if you wish i can also add some screenshots of:

- XAMPP installation
- Starting the server via XAMPP Control Panel

for the moment there is no folder for screenshots, so this also be added?

**Comment by san-coding** [comment]
> @san-coding thanks for the feedback.
> 
> if you wish i can also add some screenshots of:
> 
> * XAMPP installation
> * Starting the server via XAMPP Control Panel
> 
> for the moment there is no folder for screenshots, so this also be added?

Thank you , do add all the screenshots and mention the below steps 
-  links to install xampp (with screenshots)
- give commands to go inside the htdocs folder and git clone the project
- run xampp mysql and server (as admin) 
- go to `localhost/ShopOnline-Web` App (check if UI is loading properly)
- go to `localhost/phpmyadmin`
- create a database `shoponline`
- go to import tab and import `shoponline.sql` which is present inside the cloned repository (repo should be present inside htdocs inside xampp folder)

Try to cover all these with screenshots, no problem if you're not able to cover it all, looking forward to merging your pr @Wolfy7 🎉
-

**Comment by Wolfy7** [comment]
@san-coding create the new installation_guidelines.md file and added some screenshots.

**Review by san-coding — CHANGES_REQUESTED** [review]
image
I am unable to view the screenshots, I suggest you to just paste the screen shots inside the markdown file using (control+v) , instead of having the screenshots separate

**Comment by san-coding** [comment]
Looks good now👍🏻

**Comment by Wolfy7** [comment]
@san-coding thank you.
If its okay for you now, im done then 😊 and this can be merged

**Review by san-coding — APPROVED** [review]
Thanks you , you have been patient and have put in a lot of time and effort, we truly appreciate and look forward to more such contributions 🎉

**Pull request merged**
