### PR TITLE
Email validation added

### LINKED ISSUE #64: Email id format validation during signup
#### Current Behavior

As of now there is no email validation and so `abc@bcom` is also taken as a valid email id. In future, if features such as email verification will be implemented, such entries will create error.

#### Desired Behavior

The format of email should be validated so as `xxx@yyy.bbb` can only be given in the email field.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by princeprag**
**Description**
The email id is validated for a proper format like` xxx@bbb.iiii` and if the format is not matched the user receives a warning.

This PR fixes #64 
We can achieve the above by using `pattern ` attribute in the `input` HTML tag

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by princeprag** [comment]
@san-coding what was meant by signing the commit, did not get it?

**Comment by san-coding** [comment]
Its alright, signing commits is not mandatory for this repository, but is a good practice to be followed, you can read more [signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by san-coding** [comment]
thank you for the pull request, can you attach a screenshot of the changes reflecting in UI, just add a screenshot of the warning for a sample email address, looking forward to merging your PR 🎉

**Comment by princeprag** [comment]
Screenshot (80)
@san-coding

**Review by san-coding — APPROVED** [review]
Thanks @princeprag , we appreciate your efforts and contributions, looking forward to more such valuable contributions 🎉

**Pull request merged**
